### ISSUE TITLE
Support for indicating custom debug focus change

### ISSUE THREAD

**Issue by eltonwells** [microsoft/debug-adapter-protocol#128]
VS Code's debug focus consists of process, thread, call stack, etc. When the debugger stops, switching to another thread or call stack changes the debug focus and the debugger views refresh by re-requesting scopes, variables, etc from the DA.

Our DA would like to expand on what is considered to be in focus. We can create custom UI for changing our focus via a custom request, but is there a way to indicate this focus change from the DA back to VS Code so that it will refresh the default views in the same way? Can this be done by sending another stopped event, or is there an another event that would be more appropriate? Or would this require something new?

In Visual Studio, the workaround for this was to evaluate a fake expression, VS would re-populate its views as a side effect of the expression evaluation. Sending an event from the DA seems like the best approach, but if there's something that we could call in an extension (eg, in a onDidReceiveDebugSessionCustomEvent handler), that could also be a short-term fix.

**Comment by weinand** [comment]
No, today there is no explicit request or event in the protocol to change focus in the client or to make the client refresh its views.

Let's start a discussion about a new DAP feature (most likely a new event).
But we should avoid to use the term "focus" because a DA should never drive the UI directly in order to trigger some side effect (e.g. refresh some values).

**Comment by eltonwells** [comment]
To clarify my use of the term 'debug focus' here isn't UI, but more what specifically the debugger is looking at. In Visual Studio they call it the debug location (see Debug Location toolbar) or context (see _dispDebuggerEvents_OnContextChanged event). Does DAP have its own term for this?

**Comment by weinand** [comment]
In VS Code we use the term "debug focus" when talking about the active stack frame (which implies an active thread and debug session etc.). And this focus determines what active source location is shown in the editor (yellow arrow and line), and the target of the actions in the debug toolbar and the F1 QuickPick.

The debug focus is either changed by a received stopped event or by the user selecting a different session/process/thread/stack frame. In both cases VS Code immediately requests threads, stack frames, variables etc. 

There is no explicit extension API to change the "debug focus". However any DAP "stopped" event or any selection change in a VARIABLES or CALL STACK view could change the "debug focus" as a side effect.
 
(@isidorn please correct me if my explanation of "debug focus" isn't accurate.)

@eltonwells If I understand your request correctly, then you are asking for a new event that the DA can send to the client in order to announce that some debug session state has changed and that the client needs to refetch threads, stack frames, variables etc. in order to refresh any view that depends on the "debug focus".

What would be the exact details of that event and the associated semantics?
Here are some questions for clarifying this:
- What would be an appropriate name for the event? E.g. `SessionState` event
- What is the granularity/scope of the event? Is "all state" enough or is it possible to confine the event on a subset of all state, e.g. only to variables or only to a specific thread? 
- what happens if the event is fired from a debug adapter (debug session) that is not the session that has the "debug focus"? I would assume that in this case the event can be ignored by the client because the refetch will happen as soon as the "debug focus" changes again. That means that the event will not change the "debug focus" in the client, correct?

**Comment by isidorn** [comment]
@weinand your explanation of "debug focus" is correct.

In case somebody is interested in where exactly this is used in the UI implementation I suggest to do a find all references on the focus from the view model [here](https://github.com/microsoft/vscode/blob/da818d13feb29a52ad3ed85bb29594c5fb94bef0/src/vs/workbench/contrib/debug/common/debugViewModel.ts#L51).
For example it also influences the debug hover, watch expression evalaution, content of the variables view, breakpoint additional data...

**Comment by weinand** [comment]
Another feature request (https://github.com/microsoft/vscode/issues/70377) asks for a DAP event to make the client (frontend) refetch variables in order to refresh the UI.

Since no one replied to my [questions from above](https://github.com/microsoft/debug-adapter-protocol/issues/128#issuecomment-679148398), I will go ahead with a proposal...

We will introduce a new event "refetch" that a DA can emit in order to make the client refetch the data shown in the UI. A typical use case for this is a DA that supports to change the rendering format of data (e.g. "hex" vs "decimal"). After such a change the DA can emit a "refetch" event to make the client refresh the UI.

**Comment by isidorn** [comment]
* `VariableEvent` is a good name since we also use singular form for `BreakpointEvent`
* It feels a bit cumbersome to me to have both the `threadId` and the `stackFrameId`. I would just go for the `stackFrameId` since it is unique across threads and if there is a use case we can add the `threadId` later
* In the future if neede we can also add a `reason` field. For now it seems like all `VariableEvent` mean `update`
* makes sense for the `InitializeRequestArguments`

**Comment by puremourning** [comment]
I take it is't not expected that the UI should "jump" to the specified stack frame on this event ?

e.g. if the current UI "focus" is frame 20 and you get a `variable` event for frame 99, it should be either ignored or only a background thing (depending on the client) ?

**Comment by weinand** [comment]
@puremourning yes exactly, as mentioned indirectly in my comments above, this "event" is not a request for changing the "focus".

**Comment by puremourning** [comment]
understood, thanks a lot. I realise naming things is hard, but perhaps `variable` is either too specific or too general. Perhaps the event could be simply called `frameUpdated` - there was an update to the state of frame `<id>`, such that current evaluations are now invalid - client then typically requests the scopes/variables/exectutes watch expressions in that stack frame ? Something like that ?

I'm thinking that it would be easy to think that a `variable` event should declare a specific variable or indicate that one was created or something, but that's not necessarily the case, and it's plausible to use this event even if nothing in the eventual `variables` request changes (I guess there's a possibility that new scopes materialised, or the result of some watch expression may have changed in response to some other event etc.)

**Comment by connor4312** [comment]
- Maybe `VariableChangedEvent` would be a less ambiguous name. 
- The proposal works well for stack frames, but doesn't work for output events; if a debugger logs something is there ever a scenario in which we'd want to update it?

**Comment by eltonwells** [comment]
"Debug focus" for us is similar but has more granularity, see this from the CUDA-GDB documentation for more info.

https://docs.nvidia.com/cuda/cuda-gdb/index.html#kernel-focus

We would provide custom UI beyond the built-in session/process/thread/stack frame to change this focus, this would in turn send a custom request. In this case we would want the default views to refresh similar to when selection changes in the call stack view.

Regarding naming, I suggest InvalidateEvent, it would be more general and flexible. The DAP can indicate that one or more responses that it has sent it no longer valid, the reason could be a combination of which requests should be re-issued, including an 'all' option. The variable case for example would indicate 'variables' to reissue a Variables request.

**Comment by testforstephen** [comment]
I just think of three user scenarios that may benefit from the new event.
- Restart Stackframe
   The debugger will drop the current stack frame and re-step into the target thread.
- Hot Code Replace
   The debugger will apply the changed classes to the running JVM, then check all suspended threads to see their call stacks touching the changed classes. If so, the debugger will drop the affected stack frame and re-step into that thread.

For both scenarios above, the thread's suspend status doesn't change, but its call stack changed. And the debugger needs a way to tell VS Code client to refresh debug view. Below is the workaround we used now. If there is a new event to cover this case, that would help.
```java
// Have to send two events to keep the UI sync with the step in operations:
context.getProtocolServer().sendEvent(new Events.ContinuedEvent(thread.uniqueID()));
context.getProtocolServer().sendEvent(new Events.StoppedEvent("restartframe", thread.uniqueID()));
```
- Change settings such as formatter dynamically to refresh variable view.
  Currently if you change the variable formatter user setting, it won't take effect until the next variable request. It would be ok to provide a new event to notify client to refetch the variable list immediately.

Based on these scenarios, i think a more general sessionState is very close to these requirements.
```typescript
export interface SessionStateEvent extends Event {
    event: 'sessionState';
    body: {
        /**
         * The reason for the event.
         * Values: variable, thread.
         *
         * 'thread' - Change 'debug focus' to the target thread, refresh Variables, Watch, Call Stack views.
                      Just like what 'StoppedEvent' did.
         * 'variable' - refresh Variables view for the current focused stack frame.
         */
        reason: string;
        /**
         * Required if the reason is 'thread'.
         *
         * For example, provide a threadId if a specific thread has changed its call stacks such as
         * restarting the stack frame. Otherwise it means all threads need be refreshed.
         */
        threadId?: number;
        // I don't see how useful to provide a stackframeId if it's not current focused stackframe.
        // Can switch it to the current focus?
        // stackframeId?: number;
    };
}
```

**Comment by testforstephen** [comment]
@eltonwells if you could show some prototype to demo how the custom UI looks like, that would help others to understand the scenario better.

**Comment by isidorn** [comment]
@testforstephen I see the benefit of that more general event for your use cases. I am only worried that it might be a bit too general - sort of like a kitchen sink event. So I personally prefer something more specific what @weinand suggested. Though leaving up to @weinand to decide.

**Comment by testforstephen** [comment]
@isidorn yeah, since there is workaround to refetch the thread's call stack, it's acceptable for me to provide a specific event to refetch variable only.

For the restart stackframe and hot code replace cases, adding a new reason `stackChanged` to the current ThreadEvent is also an option.

**Comment by puremourning** [comment]
@testforstephen 

I can see from the spec we have:

- [RestartFrame](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_RestartFrame). I think that a client would indeed expect a continue followed by a stopped event here, just like with a step request. Otherwise, any step could be implemented as just some invalidation event

But reading into your use cases more, I couldn't find which DAP events/actions trigger these behaviours:

- hot code reload
- change of configuration (e.g. variable formatting)

@isidorn as a client author I think that if there are likely to be a number of similar-type events that have essentially the same client-side behaviour, I would rather implement a more generic handler and then not have to change the client for each individual server use case. My goal is to support the maximum number of servers with the minimal amount of client-side code and testing.

**Comment by weinand** [comment]
Thanks for providing helpful feedback for my proposal.
Here are some comments/answers in historical order:

@puremourning https://github.com/microsoft/debug-adapter-protocol/issues/128#issuecomment-682030390:
yes, naming is difficult - especially if I failed to convey the semantics of the `variables` event... ;-)
You suggested the name `frameUpdated` but I don't think that this name reflects the intent. Here is why: my main motivation for introducing a `variables` event was "to refresh the default views" or "to re-populate its views" (both from the initial comment) and "re-request the variable info after dynamically changing the variable format" (from https://github.com/microsoft/vscode/issues/70377). So this semantic is not really a "frame has changed in the runtime" event, but it is more of a "something in the debug adapter has changed and requires that the frontend UI needs to re-render the variable snapshot previously requested".
The `stackFrameId` and `threadId` are optional and just help to limit the UI that't need to be refreshed in the client. I would expect that debug adapters do not even care to provide them in the typical "variable format has changed" case.

@connor4312 https://github.com/microsoft/debug-adapter-protocol/issues/128#issuecomment-682034133
using the name `VariableChangedEvent` is misleading too. A client cannot use this event to track any runtime changes of a variable. The event only says that the current "snapshot" of variable values shown in the UI needs to be refreshed. A variable might be rendered in a different format but the value of the variable does not have changed at all.
You pointed out that the event doesn't work for 'output' events because they are a variable container too. This is a good point and I think that a client (e.g. VS Code) can make the decision to refresh not only the Variable view but any other location where variables are shown, e.g. watches and the debug console.  

@eltonwells 
I like the `invalidate` event but it would require additional properties to indicate to the client what got invalidated.
But I still don't quite understand what semantics do you envision for the `invalidate` event. In a previous event I asked:
> what happens if the event is fired from a debug adapter (debug session) that is not the session that has the "debug focus"? I would assume that in this case the event can be ignored by the client because the refetch will happen as soon as the "debug focus" changes again. That means that the event will not change the "debug focus" in the client, correct?

The client (e.g. VS Code) maintains the debug focus and there is no **explicit** API to change the debug focus programmatically. The only way a debug adapter can change the focus is by sending a `stopped` event. Sending an `invalidate` event to the client might change what's being displayed, but it will not change the client's notion of a debug focus in any way. Trying to maintain a different debug focus in the debug adapter and then to "trick" the UI by sending `invalidate` events is asking for trouble. 
I think the only thing a debug adapter could do is to add another "sub-level" to the current debug focus (of which the client is unaware of). But the sub-focus is always a "subordinate" of the client's debug focus.

@testforstephen 
I don't understand why the `variables` event is needed in the "Restart Frame" and "Hot Code Replace" cases. We have a `restartFrame` request which is basically a special form of `continue` and it will eventually result in a `stopped` event that will make the client request threads, stacks, and variables. There is no need for the debug adapter to emit an `variable` event in the "Restart Frame" or "Hot Code Replace" cases.
I think the `variable` event would address your need to "re-request the variable info after dynamically changing the variable format" (see you feature request https://github.com/microsoft/vscode/issues/70377).

**Comment by testforstephen** [comment]
> I don't understand why the variable event is needed in the "Restart Frame" and "Hot Code Replace" cases. We have a restartFrame request which is basically a special form of continue and it will eventually result in a stopped event that will make the client request threads, stacks, and variables. There is no need for the debug adapter to emit an variable event in the "Restart Frame" or "Hot Code Replace" cases.

Sorry to not make it clear. We don't need variable event for RestartFrame and HotCodeReplace. Currently we sent a "continued" event and a "restartframe" stopped event for both cases. Do you mean a "restartframe" event is enough for it?

**Comment by weinand** [comment]
@testforstephen yes, "restartFrame" implies "continue". If not, then this is a bug in VS Code.

**Comment by testforstephen** [comment]
A new ask is to allow refreshing a specific variable node instead of the whole variable view. For example, when i click a variable node, and execute some menu to apply new formatter, i expect to only apply to the current node only.

**Comment by weinand** [comment]
@testforstephen the semantics of context menu actions contributed to the Variables view is completely up to you. If a formatter action only applies to the selected variable, you will have to remember which variable uses which formatter so that the formatting is preserved across stepping. 
Whether the `variable` event triggers refresh of all variables in the view or only refreshes a specific variable does not make a difference from an end user perspective. However there is a performance impact.
But since DAP Variables have no ID, there is no easy way to specify a target variable in the `variable` event.

**Comment by testforstephen** [comment]
![image](https://user-images.githubusercontent.com/14052197/91709231-0abd2f80-ebb5-11ea-9077-9a64a14752bf.png)
For example, the node "cache" shows as a List structure. If clicking the context menu "View as Object" on it, the Variable event can ensure the "cache" node is expanded as an Object structure, that's OK. 

Currently it looks like VS Code will remember the expanding status of the whole Variables tree, and refetch all variables that's expanded, that achieves the goal except sending some extra variable requests.

>If a formatter action only applies to the selected variable, you will have to remember which variable uses which formatter so that the formatting is preserved across stepping.

The debugger will face the same challenge as VS Code client to map a UI variable node to the backend variable instance. Since there is no variable ID, currently what i can think of is the `evaluateName`. `evaluateName` can identify the variable in current stack frame. If the stack frame changed, it won't work.

**Comment by eltonwells** [comment]
@weinand For the `invalidate` event the reason I mentioned was meant to indicate what was invalidated, something like this (very similar to `SessionStateEvent` above, but multiple reasons can be specified):

```typescript
type InvalidateReason = 'all' | 'stackTrace' | 'threads' | 'variables' /* ...  */;

interface InvalidateEvent extends Event {
    event: 'invalidate';

    body: {
        reasons: InvalidateReason[]; 

        threadId?: number;

        stackFrameId?: number;
    }
}
```

To clarify, I didn't mean that invalidate would change focus, it would only indicate that what's being displayed is stale and needs to be updated. In my scenario our custom requests would change our debugger's more granular focus, but the thread and stack frame of interest in VS Code would remain the same.

**Comment by weinand** [comment]
@eltonwells thanks for your input.

It seems that we are converging on a solution rather quickly...

The only difference between my [initial proposal](https://github.com/microsoft/debug-adapter-protocol/issues/128#issuecomment-681892722) and yours is the name of the event and the `reasons` property which @isidorn already [suggested](https://github.com/microsoft/debug-adapter-protocol/issues/128#issuecomment-681981245).

I will prepare a new consolidated proposal...

**Comment by weinand** [comment]
Here is the consolidated proposal for the new `InvalidatedEvent`.

```ts
  /** Arguments for 'initialize' request. */
  export interface InitializeRequestArguments {

    //...

    /** Client supports the invalidated event. */
    supportsInvalidatedEvent?: boolean;
  }

  /** Logical areas that can be invalidated by the 'invalidated' event.
    'all': All previously fetched data has become invalid and needs to be refetched.
    'stacks': Previously fetched stack related data has become invalid and needs to be refetched.
    'threads': Previously fetched thread related data has become invalid and needs to be refetched.
    'variables': Previously fetched variable data has become invalid and needs to be refetched.
  */
  export type InvalidatedAreas = 'all' | 'stacks' | 'threads' | 'variables';


  /** Event message for 'invalidated' event type.
    This event signals that some state in the debug adapter has changed and requires that the client needs to re-render
    the data snapshot previously requested.
    Debug adapters do not have to emit this event for runtime changes like stopped or thread events because in that case
    the client refetches the new state anyway. But the event can be used for example to refresh the UI after rendering
    formatting has changed in the debug adapter.
    This event should only be sent if the debug adapter has received a value true for the 'supportsInvalidatedEvent'
    capability of the 'initialize' request.
  */
  export interface InvalidatedEvent extends Event {
    // event: 'invalidated';
    body: {
      /** Optional set of logical areas that got invalidated. If this property is missing or empty, a single value 'all' is assumed. */
      areas?: InvalidatedAreas[];
      /** If specified, the client only needs to refetch data related to this thread. */
      threadId?: number;
      /** If specified, the client only needs to refetch data related to this stack frame (and the 'threadId' is ignored). */
      stackFrameId?: number;
    };
  }
```

@eltonwells @testforstephen @puremourning @isidorn @connor4312 @gregg-miskelly @DonJayamanne @DanTup @pieandcakes  I'd appreciate your feedback.

**Comment by gregg-miskelly** [comment]
LGTM

CC @andrewcrawley

**Comment by DanTup** [comment]
I don't have any current need for it, but it LGTM. Is it possible there may be more values in `InvalidatedAreas` in future? If so, is it worth adding `| string` to the end or similar and stating that clients should silently ignore any values they don't know?

**Comment by weinand** [comment]
@DanTup good suggestion: I've updated the generator to generate or types with a `| string` at the for "open ended" enums. And I will a comment about silently ignoring values they don't understand.

**Comment by weinand** [comment]
Here is an updated version that incorporates the feedback from @DanTup and @isidorn:

```ts
  /** Arguments for 'initialize' request. */
  export interface InitializeRequestArguments {

    //...

    /** Client supports the invalidated event. */
    supportsInvalidatedEvent?: boolean;
  }

  /** Logical areas that can be invalidated by the 'invalidated' event.
    'all': All previously fetched data has become invalid and needs to be refetched.
    'stacks': Previously fetched stack related data has become invalid and needs to be refetched.
    'threads': Previously fetched thread related data has become invalid and needs to be refetched.
    'variables': Previously fetched variable data has become invalid and needs to be refetched.
  */
  export type InvalidatedAreas = 'all' | 'stacks' | 'threads' | 'variables' | string;


  /** Event message for 'invalidated' event type.
    This event signals that some state in the debug adapter has changed and requires that the client needs to re-render
    the data snapshot previously requested.
    Debug adapters do not have to emit this event for runtime changes like stopped or thread events because in that case
    the client refetches the new state anyway. But the event can be used for example to refresh the UI after rendering
    formatting has changed in the debug adapter.
    This event should only be sent if the debug adapter has received a value true for the 'supportsInvalidatedEvent'
    capability of the 'initialize' request.
  */
  export interface InvalidatedEvent extends Event {
    // event: 'invalidated';
    body: {
      /** Optional set of logical areas that got invalidated. This property has a hint characteristic: a client can only be
      expected to make a 'best effort' in honouring the areas but there are no guarantees. If this property is missing,
      empty, or if values are not understand the client should assume a single value 'all'. */
      areas?: InvalidatedAreas[];
      /** If specified, the client only needs to refetch data related to this thread. */
      threadId?: number;
      /** If specified, the client only needs to refetch data related to this stack frame (and the 'threadId' is ignored). */
      stackFrameId?: number;
    };
  }
```

**Comment by isidorn** [comment]
This makes sense.
VS Code will handle this event the following way: if the `areas` has only one elment which is `variables` only the VARIABLES and the WATCH view will be updated
Else: vscode will refacth all threads and their stack frames for the session. This will automatically result in CALLSTACK, VARIABLES and WATCH view updating.

**Comment by puremourning** [comment]
sounds good to me too, vimspector would do the same as what @isidorn suggested; it's simple enough to implement on the client.

**Comment by eltonwells** [comment]
Looks good, thanks @weinand

**Comment by testforstephen** [comment]
LGTM

**Comment by weinand** [comment]
@eltonwells @testforstephen a first implementation of an "invalidated" event handler is available in the next VS Code Insiders. Please give it a try and let us know whether it works for you.

**Comment by weinand** [comment]
The "invalidated" event has arrived in DAP 1.42: https://microsoft.github.io/debug-adapter-protocol/specification#Events_Invalidated
