### ISSUE TITLE
Clarify documentation for ErrorResponse Message ids

### ISSUE THREAD

**Issue by polinasok** [microsoft/debug-adapter-protocol#133]
The [spec says](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Message) the `id` is a "Unique identifier for the message". 

The [existing vscode-go DA](https://github.com/golang/vscode-go/blob/master/src/debugAdapter/goDebug.ts) does not actually use unique ids and it does not seem to be causing any problems. For example, 3000 is used for a variety of launch and attach errors and more. 

The error codes appear to be private to each implementation. What is the purpose of these error codes and should care be taken to ensure unique values?

**Comment by weinand** [comment]
Yes, error codes are private to each implementation. So the "Unique identifier for the message" means "unique within a DAP implementation".
The purpose of these error IDs is to help those extension authors that have the requirement that every error message needs a corresponding error number, so that users or customer support can find information about the specific error more easily. It is not used by VS Code.

I will update the documentation with this.
