### ISSUE TITLE
add property for controlling escaping arguments for the `runInTerminal` request

### ISSUE THREAD

**Issue by weinand** [microsoft/debug-adapter-protocol#146]
Currently it is not possible to control the escaping of the `args` property on the `runInTerminal` request. 
As a consequence the client (frontend) has to guess how to escape the arguments when passing them to a command shell.
This does not always result in the intended behavior. 

This feature request asks for a mechanism to control the escaping.

**Comment by connor4312** [comment]
I dislike "negative" boolean flags, perhaps it can be named `escapeArgs` and `supportsEscapeArgs`, with sanitization taking place unless it's specified as `false`?

**Comment by puremourning** [comment]
I think the simple solution here is just to document that arguments must never be modified or escaped. if the debug adapter wishes to use a command shell interpreter to do anything at all it must put the command interpreter as the effective argv0 (e.g. `[ '/bin/sh', '-c', 'the command line here etc.' ]`

We shouldn't add flags to indicate whether or not to 'escape for shell' because we haven't got any specification for what a 'shell' is or which shell should/would be used by the client. For example, if the user's default shell is 'powershell', is the client somehow expected to know how to escape commands for that by magic?

Currently, clients are expected, I believe _not_ to use a shell at all and rather run command supplied directly (as if by calling execvp). Am I missing something here?

**Comment by weinand** [comment]
@connor4312 yes, I don't like negative flags (e.g "dontX...")  too, but I even more dislike a flag semantics where a missing flag means "true". I prefer the "falsy" semantics: "undefined" or "false".

**Comment by puremourning** [comment]
Unless you _specify_ what escaping rules should be applied so that all clients can implement it, then not only will good-citizen clients du jour become nonconforming, but the specification becomes ruled by de facto implementation which makes it impossible for independent client implementers to actually conform.

**Comment by weinand** [comment]
@puremourning the issue we are trying to solve is https://github.com/microsoft/vscode/issues/149910.

The `runInTerminal` request should run the given commands and arguments without modifying them in any way. If the underlying implementation in the client uses a command line interpreter, the implementation will have to escape some characters in order to pass the arguments unmodified. 

I do not see a need why a debug adapter should introduce another command line interpreter. If users want to run the debuggee in the integrated terminal (which they have configured to use PowerShell), why should the DA use "bash" on top of that? 

However, some users know what they are doing and they want to pass shell syntax to the underlying command line interpreter running in the terminal. They accept the fact that doing so does not work on all platforms. They want to be able to pass arguments in a "raw" but predictable form, e.g. a `"> /tmp/out"` to pipe something into a file. They would use the new flag to do so.

**Comment by weinand** [comment]
BTW, I still like the approach to use a new `commandline` property as an alternative to combining the `args` array with a `rawArgs` flag to achieve the same.

**Comment by roblourens** [comment]
> Currently, clients are expected, I believe not to use a shell at all and rather run command supplied directly 

We are talking about the `runInTerminal` request which I think implies that the command is run in some shell and not spawned directly. When not start your debuggee in a terminal, it might be spawned directly by the debug adapter. To be clear just wondering whether you interpreted `runInTerminal` differently or missed that context. @puremourning 

I agree that the client is best suited to escape for a particular shell, being the thing that is starting the shell and sending text into it.

The `commandLine` looks nice, and makes the difference extra clear, but I like that I can set up my args for normal non-terminal debugging, then set `"console": "integratedTerminal"`, and the program with the same args is started in a terminal. If we use a different launch config property entirely then I have to partially rewrite my launch config.

**Comment by roblourens** [comment]
Oh and also if I want to pass a real space in an arg with `commandLine`, now I have to figure out how to escape it in my launch config 😁

**Comment by roblourens** [comment]
Sorry for the stream of consciousness but actually you are saying that I would continue to use `args` to get escaped args, but switch to `commandLine` to pass unescaped args?

**Comment by weinand** [comment]
@roblourens you asked:
>... you are saying that I would continue to use args to get escaped args, but switch to commandLine to pass unescaped text?

yes, that would be my second proposal.

**Comment by int19h** [comment]
Does it actually need a separate property though? Perhaps just allow "args" to be a string rather than an array? It feels like it'd make more sense from the naming perspective, at least - "commandLine" sounds like the entirety of the command line, but in practice you'd still have the actual run target specified separately.

**Comment by puremourning** [comment]
> > Currently, clients are expected, I believe not to use a shell at all and rather run command supplied directly 
> 
> 
> 
> We are talking about the `runInTerminal` request which I think implies that the command is run in some shell and not spawned directly. When not start your debuggee in a terminal, it might be spawned directly by the debug adapter. To be clear just wondering whether you interpreted `runInTerminal` differently or missed that context. @puremourning 
> 
> 

I know it's about run in terminal. But that does NOT imply a shell. A pty is not a shell. 

> 
> I agree that the client is best suited to escape for a particular shell, being the thing that is starting the shell and sending text into it.
> 

 
I don't think the client should spawn a command shell at all. 


> 
> 
> The `commandLine` looks nice, and makes the difference extra clear, but I like that I can set up my args for normal non-terminal debugging, then set `"console": "integratedTerminal"`, and the program with the same args is started in a terminal. If we use a different launch config property entirely then I have to partially rewrite my launch config.

**Comment by weinand** [comment]
`runInTerminal` is used to start a debuggee in a new or existing interactive terminal. That terminal uses a command line interpreter (aka "shell").
Running a command in that interpreter requires the use of the correct syntax which depends on the shell used.

**Comment by puremourning** [comment]
> This optional request is sent from the debug adapter to the client to run a command in a terminal.

> This is typically used to launch the debuggee in a terminal provided by the client.


Nothing here implies a command interpreter is required. It states  it's for running the debuggee, not a shell. 

To be clear there is no need to run a shell to run a program. Windows explorer is a shell, bash is a shell. these call system calls (execpe / createprocess) that create processes and attach them to pseudo terminals. Given the above definition it's perfectly reasonable and sensible to launch the requested image whiteout using and intermediary (and pointless) command interpreter.

**Comment by weinand** [comment]
Yes, a shell is an implementation detail of `runInTerminal`.
The spec for `runInTerminal` does not mention "shell" anywhere.

However, when a user creates a debug config for launching the debuggee in VS Code's integrated terminal, then users are very well aware of the fact what shell is running in the integrated terminal. 
Now they want to use shell features in the debug config.

We are not trying to solve problems for the case where no "pointless command interpreter" is used.
We are to to solve problems for the case where "command interpreter" is used because the user wants to use it.

**Comment by puremourning** [comment]
> This makes the most sense to me: as a user, either you let the tooling handle all the quoting and escaping, or you're in full control but also responsible for all of it.

and if you're in full control of it, you can be the one to instruct a shell to be executed, i.e,:

* `/bin/bash -c 'my command here > output.log'`
* `C:\windows\cmd.exe /c my command here > output.log`
* etc.

**Comment by weinand** [comment]
@puremourning 
> This makes the most sense to me: as a user, either you let the tooling handle all the quoting and escaping, or you're in full control but also responsible for all of it.

That's basically one of the proposals here. What problems do you see with that approach?

**Comment by int19h** [comment]
I think the contention here is that, for clients that implement "runInTerminal" by doing exec() directly, the semantics of "commandLine" is unclear since you're supposed to provide an array, but there are no clear rules according to which the command line is to be split.

But then I'd expect such clients to not support "commandLine" at all. It would still be a conditional feature with a client feature flag, right?

**Comment by weinand** [comment]
`runInTerminal` is not a general mechanism to launch programs. 
It is a mechanism to launch programs in a "terminal", or to be more precise in the client's "integrated" terminal or in an "external" terminal.
If your client does not support these types of terminals, then there is no need to implement the request.

So what terminals out there do not use command interpreters?

**Comment by weinand** [comment]
I don't get why you would want to go through all the hassles of using `runInTerminal` if the result is not what you need? If using `exec*()` directly is what you want, then don't use `runInTerminal`.
BTW, the default way to launch debuggees (without a shell!) is not handled by `runInTerminal` at all, but is completely left to the debug adapter (e.g. by using spawn() or fork/exec).

The purpose of `runInTerminal` is to launch debuggees in the same way (and terminal) as if the user would have typed the command on the command line (including shell characters). So the command history would show the command to launch the debugger and moving through the command history gives users a way to modify arguments etc.

**Comment by roblourens** [comment]
Whether or not terminal implies shell - I get the distinction and now understand where you are coming from - I think this discussion shows exactly why we didn't want to allow shell characters in the first place. When you create a launch config that includes shell characters, now that launch config is tied to a particular shell. The user is responsible for configuring this that based on their knowledge of the client's shell support and personal configuration. This is awkward but I feel that it's the tradeoff that we have accepted in deciding to support this use case.

If they write powershell in `args`, and the client does not spawn a powershell shell, it's not the client's failure to respect the DAP spec, it's the user's issue for misconfiguring their launch config.

So then it follows that if someone implements a DAP client that doesn't spawn any shell for a `runInTerminal` request, it's still the user's responsibility to set up their launch config to account for this.

**Comment by puremourning** [comment]
I guess this sort of got a little off the original topic, and I suppose that's probably my fault. I suppose we can put aside whether or not it's correct to launch the app as specified, or first launch a shell, and ask the shell to launch the app, and accept that both are reasonable interpretations and behaviours:

1. We've agreed that _by default_ the arguments should be used verbatim, and therefore if a client elects to start a shell, they are responsible for the quoting and escaping of the command line. (@weinand  wrote "arguments strings are passed to the command unmodified and they are not interpreted by an intermediate command line interpreter".)
2. We also agree that it's undesirable for users of such clients who are relying on it _not_ doing that to be broken by doing this.
3. I hope we can at least agree that _both_ approaches (using a shell, or not) are _valid_ interpretations of the specification.

Given that, I guess the proposal is workable, if a little difficult to explain. In the interests of contributing something positive to this, I'd suggest some wording something like:

---

## Launching the application

Client implementations are free to launch the application however they choose including issuing the command to a command line interpreter. However the command line in `args` (including its argument strings) are passed to the command unmodified and they are not interpreted by an intermediate command line interpreter. As a result, clients which use a command line interpreter are responsible for escaping any special shell characters in the `args` string.

Some users may wish to take advantage of shell processing in the `args` string. For clients which implement `runInTerminal` using an intermediary command line interpreter, the `argsCanBeInterpretedByShell` (TBD: bikeshed about name of field) item can be set to `true`. In this case the client is requested _not_ to escape any special shell characters in the `args` strings.

Specifically the meaning if `argsCanBeInterpretedByShell`: `true` is:

1. If the client does not use an intermediary shell to launch the application, it has no effect.
2. If the client uses an intermediary shell to launch the application, then the client _must not_ attempt to escape shell special characters, but _may_ escape quotes or other characters as necessary in order to pass the command to the interpreter successfully.

---

Thoughts?

If we define it that way, I don't see the need for a client capability. The point is that what can a debug adapter do if the client does't have the capability and the user requested it? Just fail?

**Comment by weinand** [comment]
@puremourning thanks for putting my proposal into proper words.

> If we define it that way, I don't see the need for a client capability. The point is that what can a debug adapter do if the client does't have the capability and the user requested it? Just fail?

If we had a client capability then a debug adapter could post an alert and warn the user that shell syntax doesn't work because no intermediate shell is used.

---

Here is another version of the proposal:

### Launching the debuggee from the debug adapter

Debug adapters are free to launch the debuggee however they choose. Typically the debuggee is launched as a child process and its output channels are connected to a client's debug console via DAP `output` events. If a debug adapter wants to launch the debuggee in a terminal that is integrated into the client or in a terminal that runs outside of the client (but still configured and managed from the client), it can use DAP's `runInTerminal` request to use those terminals.

### Implementing `runInTerminal` in the client

Client implementations of `runInTerminal` are free to run the command however they choose including issuing the command to a command line interpreter (aka 'shell'). Argument strings passed to the `runInTerminal` request must arrive unmodified (verbatim) in the command to be run. As a consequence, clients which use a shell are responsible for escaping any special shell characters in the argument strings to prevent them from being interpreted by the shell.

Some users may wish to take advantage of shell processing in the args string. For clients which implement `runInTerminal` using an intermediary shell, the `argsCanBeInterpretedByShell` property can be set to true. In this case the client is requested not to escape any special shell characters in the argument strings.

Specifically the meaning if `argsCanBeInterpretedByShell`: true is:
- If the client does not use an intermediary shell to launch the application, it has no effect.
- If the client uses an intermediary shell to launch the application, then the client must not attempt to escape shell special characters [I'm not sure about the: "but may escape quotes or other characters as necessary in order to pass the command to the interpreter successfully." I'd prefer that the client does not escape at all, but I don't know whether this is possible.]

**Comment by puremourning** [comment]
> Typically the debuggee is launched as a child process and its output channels are connected to a client's debug console via DAP output events

How about adding:

> Typically the debuggee is launched as a child process and its output channels are connected to a client's debug console via DAP output events. However, this has certain limitations, such as not being able to write to the terminal device directly and not being able to accept standard input. For those cases, launching the debuggee in a terminal is preferable.

Regarding:

> "but may escape quotes or other characters as necessary in order to pass the command to the interpreter successfully." I'd prefer that the client does not escape at all, but I don't know whether this is possible

I guess we have to allow it. If the client launches the app with `/bin/csh -c "$cmd"` or `/bin/bash -c "$cmd"` or `xterm -e "$cmd`" , then they _must_ be allowed to esape `"` characters, else it wouldn't be possible to use them at all... or are you thinking that that's _also_ the responsibility of the user configuring the arguments in their launch config ?

**Comment by weinand** [comment]
@puremourning thanks for the improved wording. I'll create a new version...

 > ... or are you thinking that that's also the responsibility of the user configuring the arguments in their launch config ?
Yes, that was my thinking. Leaving all the escaping to the user is less confusing than having a mix.

**Comment by puremourning** [comment]
> @puremourning thanks for the improved wording. I'll create a new version...
> 
> > ... or are you thinking that that's also the responsibility of the user configuring the arguments in their launch config ?
> 
> Yes, that was my thinking. Leaving all the escaping to the user is less confusing than having a mix.

I fear that will even further bind your users to your internal implementation and the internal implementation details of the debug adapters, but as this won't actually affect me, I don't have "skin in the game" as they say :D

**Comment by roblourens** [comment]
Sorry, I lost track of what we are proposing right now, is all of the above text to go into the RunInTerminalRequest description? It seems like more detail than needed for the request.

And are we settling on not including a client capability? It seems like the behavior would be better to have a client capability and let the debug adapter decide what to do, rather than sort of fail silently.

**Comment by weinand** [comment]
@roblourens the [description from above](https://github.com/microsoft/debug-adapter-protocol/issues/146#issuecomment-1167370423) tries to explain the rational behind this new property. The fact that we have had this rather lengthy discussion is evidence that the existing specification is inadequate. 

Whether we will fold the full description into the `runInTerminal` request is a valid concern. For now let's use the description as the spec of the new feature.

Client capability:
Yes, I agree, having a client capability (`supports`)  makes it possible to show a warning if a launch config uses the flag when it is not supported.

**Comment by roblourens** [comment]
In https://github.com/microsoft/debug-adapter-protocol/issues/146#issuecomment-1167370423, I think the first paragraph could be worked into the overview page for DAP, in "Launching and Attaching", if we need more context on why an adapter would use `runInTerminal` at all.

The second paragraph makes sense in the description for `runInTerminal`, with some shorter description on `argsCanBeInterpretedByShell` itself. Working on this.

**Comment by weinand** [comment]
@roblourens great, thanks!

**Comment by roblourens** [comment]
Sent this proposal, take a look: https://github.com/microsoft/debug-adapter-protocol/pull/305
