### ISSUE TITLE
Message for reloading code on file modification

### ISSUE THREAD

**Issue by fabioz** [microsoft/debug-adapter-protocol#176]
For `debugpy` it'd be interesting to have a message which allows the debugger to be notified of changes to an edited file so that it can reload the contents of the file in the debugger.

**Comment by weinand** [comment]
The recommended way to address this problem is to run a file watcher from the debug adapter. This is what all debug extension that support hot reload do.
Sending file change notification from the client would only work for simple cases. Whenever there is a build process that transforms the source into some intermediate format, VS Code does not know what the resulting file is.
