### ISSUE TITLE
Add support for "showMessage" notifications

### ISSUE THREAD

**Issue by NipunaRanasinghe** [microsoft/debug-adapter-protocol#193]
I'm working on a DAP implementation for the Ballerina language and have come up with a requirement to display a particular message in the user interface in some contexts. Even thought the LSP supports `window/showMessage` notifications to handle such use cases, it seems to me that there is no any similar support being exposed in the DAP. Is there any specific reason for that or do we have any plans to add similar support in the near future?

**Comment by ishche** [comment]
In our debugger, we use output message and custom message handler on the vscode site to have this functionality.

**Comment by NipunaRanasinghe** [comment]
> In our debugger, we use output event and custom message handler on the vscode site to have this functionality.

@ishche Yeah of course we can have our own customized implementations to have this functionality, but I'm just curious why the DAP is missing such a mainstream capability :) BTW would you mind sharing your implementation(maybe the GitHub link?), if it's public?

**Comment by puremourning** [comment]
> <snip> customised <snip> to have this functionality

... in only one specific DAP client.

---

There was a recent discussion about this exact feature recently (searching for `showMessage` in the issues section of GitHub finds it): here was my position on it then: https://github.com/microsoft/debug-adapter-protocol/issues/175#issuecomment-816832330 - adding here as this is more on-topic.

**Comment by weinand** [comment]
I fully agree with @puremourning https://github.com/microsoft/debug-adapter-protocol/issues/175#issuecomment-816832330 on this:

The DAP is not meant to "drive" a UI - it only provides "strings" for the UI driven by the client. And DAP does not make assumptions about the client's UI, e.g. whether it is a interactive/graphical UI, or a command line, or just a non-interactive test driver.

Having a "showMessage" would violate that principle.

If you really need "showMessage" functionality, just implement it in the extension (because the extension is VS Code specific and can make assumptions about the UI).

**Comment by NipunaRanasinghe** [comment]
Thanks for your inputs @puremourning and @weinand. It makes sense after your explanation and I think implementing the functionally in the vscode side as a custom extension might be the better option here.
