### ISSUE TITLE
DataBreakpointInfoRequest clarification

### ISSUE THREAD

**Issue by fbrosseau** [microsoft/debug-adapter-protocol#198]
Hello,

In DataBreakpointInfoRequest, there are currently two fields.

```
// Reference to the Variable container if the data breakpoint is requested for a child of the container.
variablesReference?: number

// The name of the Variable's child to obtain data breakpoint information for.
// If variablesReference isn't provided, this can be an expression.
string: name
```

This leads to two usecases
1- variablesReference is set. This case is clear and unambiguous
2- variablesReference is not set. This means name "can be an expression". 

My question is about # 2. What is the expression's scope? Global?
Unless I am misunderstanding the intent of usecase # 2, should there be an optional `frameId?: number` field, so that this can be unambiguously implemented, in the same way as the existing `Evaluate` request? Otherwise I do not think it is possible to implement watchpoints on things that are directly local variables (or at least unambiguously).

**Comment by weinand** [comment]
Yes, a `frameId` property is missing to make this request usable with expressions.

How should we fix that?
- add an optional `frameId` property and a new capability so that clients can figure out whether a debug adapter implements expression evaluation for all scopes,
- remove the option to pass expressions and a new capability so that clients can figure out whether a debug adapter has (limited) support for expressions or not.

Since no client has complained about the missing `frameId` property, I don't think that the expression feature is broadly used in DAs.

**Comment by connor4312** [comment]
From the JS side, data breakpoints don't exist. But if they do it'll almost certainly have to be based on a variables reference. Most debuggers would require that as well, I think; asking for any changes to a variable named `foo` could break in the library code just as easily as intended user code.

So both suggestions makes sense to me, though I would want to hear from implementors who actually use data breakpoints too.

**Comment by haneefdm** [comment]
@connor4312, our users use data breakpoints because it is done in HW (IoT CPUs, limited number available) and is super useful, saves days of debug time. Embedded CPUs are harder to debug in general and stuff like this helps.

And for sure, if arbitrary expressions are used, then `frameId` disambiguates the data breakpoint and avoids confusion. We currently just reject data breakpoints when variableRefrence is not given. In other words, they don't use it with our DA because it is not possible. First, because VSCode does not request it and then we don't allow it.

I bet they will use it from the Watch window if available because it is a lot more convenient to have global vars. readily available in Watch window rather than hunting for them in the Variables after every pause.

Rather than removing the expression feature from the DAP, I would add the optional `frameId`. and maybe VSCode will eventually make such requests.

**Comment by weinand** [comment]
I agree: let's add an optional `frameId`.

**Comment by gregg-miskelly** [comment]
For what it is worth, the way we solved this in full Visual Studio was to extend EvaluateResponse --

```json
interface EvaluateResponse {
    // ...

    /**
     * Reference integer for the evaluated expression result. This can be used when referencing the result on further requests.
     * The value should be less than or equal to 2147483647 (2^31 - 1).
     */
    evaluateResponseReference?: number;

    // ...
}
```

And Data
