### ISSUE TITLE
Make additional an variables request, that adheres to same principles as breakpointsRequest

### ISSUE THREAD

**Issue by theIDinside** [microsoft/debug-adapter-protocol#244]
Currently, variablesRequest is fired for each variablesReference that is "tracked". This creates a weird dynamic, where the debug adapter never knows what "variable references" or "scopes" are visible, since the requests come arbitrarily and one-by-one.

If instead, an additional method / feature was provided, where the *entire* variablesReferences are passed as an array (i.e. the "visible ones" in the UI) the debug adapter can make these decisions, which it currently can not:

It can scan the array of variablesReferences and see which ones are currently viewed and active (since the ones who aren't, won't be in the array, sort of like how breakpointsRequest work; the ones who aren't in the request, should be removed/unset from the debug adapter backend) and thus make decisions on what it needs to do in the backend accordingly. If the backend (i.e. the debugger, or the debug adapter) is tracking a large amount of data, it will *have* to update the state information for all this data, because it can't know if the children of a variablesReference is visible or not. This incurs unnecessary overhead, for no reason at all.

A simple scenario to explain;
There are 3 scopes open, for 3 structured types;
- Foo,
- Bar,
- Baz

Since they've all been "opened", the debug adapter will have to fetch the information about it's members (or elements, if it's an array). This is all fine and well. And if the scopes never are "folded out" in the UI; the children of these types won't have to be "tracked" by the backend or the debug adapter.

But if the user then folds in, Bar and Baz, the debug adapter and the backend will have no way (ever) of knowing this. This means, that for any consecutive calls, it will have to either build large scaffolding (unnecessarily) to track approximately if requests have been made for a scope and thus "freeze" the updating of the sub members to be performant.

Solution:
Introduce an additional feature, that instead of individual variablesRequests, have a variables request that requests _all_ active "scopes" for a thread, for instance. This will make it so, the debug adapter and the backend can *easily* know, which of it's tracked variables will need to be updated.

**Comment by weinand** [comment]
@theIDinside Since this is a feature request for the Debug Adapter Protocol; I've moved it from VS Code to the DAP repo.

**Comment by weinand** [comment]
you said:
> Currently, variablesRequest is fired for each variablesReference that is "tracked". This creates a weird dynamic, where the debug adapter never knows what "variable references" or "scopes" are visible, since the requests come arbitrarily and one-by-one.

I don't agree: the debug adapter (DA) knows exactly what "variable references" or "scopes" are visible because the client (e.g. VS Code) sends `variables` requests only for those scopes and variables that are visible. And if the user expands another scope or structured variable, a single `variables` request  is issued to fetch all children in one go (and not one-by-one as you said). So the client can only issue `variables` requests for "variable references" that the DA has handed out previously. There are no "surprises".

In addition, I really don't think that the DA should "track" what variables are visible or not. Variables (and `variableReferences`) are short-living. They are only valid while execution has stopped. After a resume (or a single step) all state must be discarded anyway. So it does not make sense for a DA to build sophisticated data structures that mirror what the client UI shows.

Typical DAs have a flat hashmap that maps a variable reference to some data received from the "real" backend debugger.
Initially (after the debuggee has stopped and a stackframe has been returned) this map only contains entries for the scopes (because that's the only thing the client can ask for). And when the first level of variables are requested by the client, then the DA will add more variable reference to the hashmap. But after a "continue" (or "next" request) the hashmap must be cleared.
 
you said:
> If .. an additional method / feature was provided, where the entire variablesReferences are passed as an array (i.e. the "visible ones" in the UI)

I do not see a big advantage: in both cases you need the same hashmap to lookup variable references. With the `variables` request there are multiple single-ref lookups, with your array proposal there is one multi-ref lookup which actually results in a problem:
Your approach is not incremental because you assume a single array that contains everything visible (that's the reason why you compare it with the `breakpoints` request). But the situation with variables is different than breakpoints: you rarely have thousands of breakpoints in a single file. But with variables a user can drill down in a big array expanding thousands of items and in that case the client UI would have to refetch all variables again for every expand (because it is not incremental).

**Comment by theIDinside** [comment]
I don't think I made my point very well. You're absolutely correct in that there are never any "surprises"; however, if a debug adapter (or a debugger, in the case of GDB) has some nifty and performant solution for tracking variables (as is the case with GDB/MI Variable Objects), once the user has "expanded" a scope, GDB is now forced to manage that scope, whether or not the user folds that scope back in (for instance, to perform single-stepping to avoid fetching/reading unnecessary data).

If variablesRequest or an adjacent method, did what breakpointsRequest do, i.e. send variablesRequest for a thread, for all visible variables, the debug adapter (and in this particular example, GDB and it's Variable Objects) can know exactly up front what it will need to continue to track. This is currently impossible with the current setup, since variablesRequest come in arbitrary sequences, from the perspective of the debugger, thus left with no room for nifty optimizations or features. I get that GDB is technically an edge case, as there are a multitude of debuggers.

I am not arguing for the replacement of variablesRequest, but it would be nice with a feature that adds, supportedOneShot or something.

>Your approach is not incremental because you assume a single array that contains everything visible (that's the reason why you compare it with the breakpoints request). But the situation with variables is different than breakpoints: you rarely have thousands of breakpoints in a single file. But with variables a user can drill down in a big array expanding thousands of items and in that case the client UI would have to refetch all variables again for every expand (because it is not incremental).

I don't see how this is true. Sending the hypothetical variablesRequestOneShot (bad name, but bear with me) with an args parameter that contains all variablesReferences does not force the UI to refetch all variables for every expand. It just signals to the debug adapter which ones it wants, in one call instead of consecutive calls. The hypothetical response from such a chained call, would be `[r1, r2, r3, ...]`. Just as variablesRequest aims to be lazy (i.e. give me what i want, when I want it) so would this be. If VSCode has gotten no "ContinueEvent" or some execution event, I can't see how VSCode would be required to fetch it every time the variables are expanded, if for instance, the user unfolded-folded-unfolded, all within the same "stop".

> But after a "continue" (or "next" request) the hashmap must be cleared.
I would argue that continue and next requests shouldn't clear the map, unless the DA/backend can resolve or approximate that it has left the stack frame it's executing in. If we clear the cache at every step, or even after every continue, we *could* be performing a lot of unnecessary work, for absolutely no gain at all, except the minor simplification of the code of course (a naive approach of clear-at-every-request is of course easier to implement).

In the end, I might be looking too narrowly through the lens of GDB here, I suppose.

**Comment by weinand** [comment]
@theIDinside could you please answer my last question?

**Comment by weinand** [comment]
Closed due to lack of information.
