### ISSUE TITLE
Please Disambiguate supportTerminateDebuggee and supportsTerminateRequest Capabilities in Documentation

### ISSUE THREAD

**Issue by ericdrobinson** [microsoft/debug-adapter-protocol#249]
## Background

The `supportTerminateDebuggee` and `supportsTerminateRequest` capabilities both deal with terminating a debuggee but their documentation does not provide insights as to how they are different. 

If the `supportTerminateDebuggee` capability is supported, it enables the `terminateDebuggee` attribute on the 'disconnect' request. The `terminateDebuggee` attribute documentation claims the following:

>Indicates whether the debuggee should be terminated when the debugger is disconnected.
>If unspecified, the debug adapter is free to do whatever it thinks is best.
>The attribute is only honored by a debug adapter if the capability 'supportTerminateDebuggee' is true.

If the `supportsTerminateRequest` capability is supported, it enables the Terminate Request. The Terminate Request documentation claims the following:

>The ‘terminate’ request is sent from the client to the debug adapter in order to give the debuggee a chance for terminating itself.

Both of these appear to deal with "terminating the debuggee" and there is absolutely zero language about how they are intended to be used. In order to understand them, I had to hash out the details with @weinand while simultaneously trying various combinations of the two in my debug adapter implementation (with VS Code as client).

## Trial And Error Investigation

In VS Code, the `terminateDebuggee` option will tell you whether the UI's "Stop" or "Disconnect" button was pressed. This applies to Debug Sessions started with either Attach or Launch.

In VS Code, the Terminate Request [[currently?](https://github.com/microsoft/vscode/issues/143991)] **is only called for Debug Sessions started with a Launch configuration**. When the Terminate Request is supported, the UI's "Stop" button will trigger the Terminate Request call and **not** call the Disconnect Request. However, the Debug Session is not automatically stopped. Rather, if the debug adapter is able to terminate the debuggee as a result of handling that request, then it is also expected to trigger a Terminated event. The Terminated event will in turn call the Disconnect Request. If a Terminated event is **not** triggered (e.g. if the termination process was stopped for some reason), then the Debug Session will continue. If the user presses the UI's "Stop" button a _second time_, then the Terminate Request is **not** called and the Disconnect Request is instead, indicating a "forced shutdown". This enables VS Code (at least?) to support a two-stage termination process with adapters that support it.

## The Issue

While the definitions are "technically correct", they are too vague to be of any serious use without deeper investigation. Nowhere does the Terminate Request documentation explain the details about how it is intended to enable a two-phase termination setup or provide an example of when that might be the case (e.g. this enables the debug adapter to send `SIGINT` initially and, if that fails to terminate the debuggee, then `SIGKILL` when the fallback Disconnect Request is triggered).

If _all of the above_ is "client-side implementation detail" and some clients could, say, always send both Terminate Requests and Disconnect Requests when they are enabled, then the clients should document this fact. Currently VS Code [does not have any such documentation](https://github.com/microsoft/vscode/issues/135390). However, if the _intent_ of the Terminate Request is to enable this two-phase shut down then it would be better to explicitly state the expected flow in the documentation here so that Debug Adapter implementers can have proper expectations set and not fear having to deal with the protocol's **Undefined Behavior** and figure out how to implement client-specific implementations...

## The Request

Is it at all possible to expand upon the current documentation for these two features of the protocol such that more clear expectations may be set for how they are intended to be used?

**Comment by weinand** [comment]
I will not change the description of the capabilities `supportTerminateDebuggee` and `supportsTerminateRequest` because their descriptions sufficiently explains what optional features the capabilities announce.
 
I propose to change the description of the `terminate` request as follows:

> The `terminate` request is sent from the client to the debug adapter in order to shutdown the debuggee gracefully. Clients should only call this request if the capability `supportsTerminateRequest` is true.
Typically a debug adapter implements `terminate` by sending a software signal which the debuggee intercepts in order to "clean things up properly" before terminating itself.
Please note that this request does not directly affect the state of the debug session: if the debuggee decides to "veto" the graceful shutdown for any reason by not terminating itself, then the debug session will just continue.
Clients can surface the `terminate` request as an explicit command or they can integrate it into a two stage "Stop" command that first sends `terminate` to request a graceful shutdown, and if that fails uses `disconnect` for a forceful shutdown. 

I propose to change the description of the `disconnect` request as follows:

> The 'disconnect' request asks the debug adapter to disconnect from the debuggee (thus ending the debug session) and then shut down the debug adapter. In addition, the debug adapter must terminate the debuggee if it was started with the `launch` request. If an `attach` request was used to connect to the debuggee, the debug adapter must not terminate the debuggee.
This implicit behavior of when to terminate the debuggee can be overridden with the optional arguments `terminateDebuggee` and `suspendDebuggee` (which are only supported by a debug adapter if the corresponding capabilities `supportTerminateDebuggee` and `supportSuspendDebuggee` are true).

**Comment by ericdrobinson** [comment]
That is _way_ more clear! Thank you very much for adding so much detail! ❤️
