### ISSUE TITLE
Allow DAP to set granularity for steps

### ISSUE THREAD

**Issue by Enerccio** [microsoft/debug-adapter-protocol#26]
For a lot of languages it makes sense to set granularity for steps. For instance, in any bytecode language it makes sense for step normally step over lines, but sometimes it should step over bytecode instead.

**Comment by Enerccio** [comment]
it could have these values:

* line - step will step to next line
* logical - step will step to next logical step (for instance if I have two statements on one line, to that statement)
* fine - step will step in smallest possible step (for instance next instruction)

**Comment by dgozman** [comment]
Also note that in JavaScript, developers sometimes need to step into asynchronous function invocation instead of a regular synchronous step. Consider this example, where it is convenient to step from `paused` directly to the arrow function, instead of setting up an inline breakpoint.

```
const somePromise = retrievePromise();
paused: return somePromise.then(value => console.log(value));
```

Chrome DevTools does this async step in by default, since it's usually more useful to the developer, and leaves a separate "step" for synchronous stepping if needed.

**Comment by weinand** [comment]
Feature #110 addresses stepping granularities.
