### ISSUE TITLE
Check whether 'final' makes sense for VariablePresentationHint.visibility

### ISSUE THREAD

**Issue by rillig** [microsoft/debug-adapter-protocol#289]
>   visibility?: 'public' | 'private' | 'protected' | 'internal' | 'final' | string;

The word 'final' does not intuitively belong in this list since it is not about visibility but about _modifiability_, which is an orthogonal concept.

For example, Java allows `public static final` variables. Should a debug adapter choose `public` or `final` in such a case?

**Comment by weinand** [comment]
`final` might not be the best example for a "visibility" attribute, but since the attribute's effective type is `string`, the list of example values is neither binding nor exhaustive. In addition, since DAP is just a UI protocol, there is no semantic associated with the strings.

Removing the `final` would make the set of examples more clear, but in order to ensure backward compatibility of the schema I propose that we keep `final`. 

And to answer your question about `public static final`, a DA could just return `public static final`.
