### ISSUE TITLE
Add optional location information to Variables

### ISSUE THREAD

**Issue by connor4312** [microsoft/debug-adapter-protocol#368]
I propose adding a few new properties to variables

```
  /**
   * The source location where the variable was declared.
   */
  source?: Source;

  /**
   * An optional line number where this variable was declared.
   */
  line?: number;

  /**
   * An optional column number where this variable was declared.
   */
  column?: number;
```

This would allow jumping to definitions as requested in https://github.com/microsoft/vscode-js-debug/issues/838. This would be handy, though there was not a lot of passion around that feature request on js-debug. Maybe other DA's would want to use it though.

**Comment by roblourens** [comment]
This seems like pretty limited applicability. I wonder if there's a simpler way to fix it up just for the case with a function, for example, in vscode we have a link detector on variable values, and if you include a `location: /path:123` property on the function, users can cmd+click to jump there.

Related, @minsa110 was asking for a "go to definition" from the variables explorer in notebooks. It's a little more practical in that context because most variables come from a single document and maybe one can reverse engineer the locations on demand.

**Comment by connor4312** [comment]
V8 does give us a magic `[[FunctionLocation]]` internal property. I don't really like the idea of treating 'magic properties' special, but we could definitely linkify things that look like locations (either file paths or URIs, URIs would be more general.) And we could parse locations that are children of the debug sessions's workspace folder to look a bit nicer.

I like that solution more than my proposal 😛

**Comment by roblourens** [comment]
Oh yeah, we have https://github.com/microsoft/debug-adapter-protocol/issues/343 already :)

**Comment by roblourens** [comment]
> we could definitely linkify variable values that look like locations (either file paths or URIs, URIs would be more general.)

This does already work today, you can cmd+click the value of `[[FunctionLocation]]`

**Comment by sandipchitale** [comment]
@roblourens I was not able to cmd+click the value of `[[FunctionLocation]]` in VSCode JS debugger when debugging an extension even though I see the source location. Has this made to the released version of VSCode?
