### ISSUE TITLE
Clarify impact of StackFrameFormat

### ISSUE THREAD

**Issue by tromey** [microsoft/debug-adapter-protocol#411]
While working on the gdb implementation of DAP, I wasn't sure what to do with `StackFrameFormat` -- in particular, what impact it ought to have.

My guess is that many of the parameters ought to affect the `name` of the returned stack frame.  It would be great if the spec could spell this out.

Some parameters, like `line` and `module`, seem redundant, though.  And even `parameterValues` seems redundant with the scopes request.

**Comment by connor4312** [comment]
I'm not sure actually. @gregg-miskelly do you have historical context on this one?

**Comment by gregg-miskelly** [comment]
> My guess is that many of the parameters ought to affect the `name` of the returned stack frame. It would be great if the spec could spell this out.

Correct

> Some parameters, like `line` and `module`, seem redundant, though. And even `parameterValues` seems redundant with the scopes request.

By "redundant" do you mean the client could produce the name itself in some way? If so, that is correct, but it is done this way so that:
1. The debug adapter can format the string in a syntax that makes sense in their language
-and-
2. The debug adapter may be able to far more efficiently produce the value of just the arguments to the function than the using a `scopes` request

**Comment by tromey** [comment]
> By "redundant" do you mean the client could produce the name itself in some way?

I just meant that the line and module are already present in the `StackFrame`, so I didn't understand if this flag means the client is required to also put the information into `name`.

**Comment by connor4312** [comment]
Thanks for the context. I suggest replacing "for the stack frame" to "in the `StackFrame.name`" for the relevant properties.

**Comment by tromey** [comment]
A related question here is what does `parameters` mean -- how does it differ from `parameterTypes`, `parameterNames`, and `parameterValues`?

**Comment by gregg-miskelly** [comment]
I think it was a mistake to include `parameters`. I believe the author of this part of the spec was borrowing too heavily from Visual Studio's debug interface ([`FIF_FUNCNAME_ARGS`](https://learn.microsoft.com/en-us/visualstudio/extensibility/debugger/reference/frameinfo-flags?view=vs-2022&tabs=csharp)) but here is how I believe this was intended to work:

* `parameters` == false: Don't indicate anything about the parameters to the method. Debugger doesn't need to even look at `parameterTypes`, `parameterNames` or `parameterValues`
* `parameters` == true: Include the arguments in a way that makes sense for the language being debugged, using `parameterTypes`, `parameterNames`, and `parameterValues` as makes sense

**Comment by JustinGrote** [comment]
Sorry to necro this thread, but I was curious in regards to the parameters surfacing, what about the actual values/arguments specified to those parameters?

For example if I have this call stack:
![Image](https://github.com/user-attachments/assets/fc8f13ce-b704-44e1-8660-afeef701455b)

Not sure where I am supposed to surface those Argument values, since it's not a property on the StackTrace itself or the Source

**Comment by connor4312** [comment]
The guidance would be to put them in the `StackFrame.name` in a 'way that makes sense' for users of the DA.

If I had my druthers, it would be a bit more structured, but we are where we are.

I will make a PR to clarify `StackFrameFormat` a bit.

**Comment by JustinGrote** [comment]
Thank you!
