### ISSUE TITLE
Debug Adapter protocol definition clarification

### ISSUE THREAD

**Issue by PavelSosin** [microsoft/debug-adapter-protocol#46]
I propose to clarify Debug Adapter protocol definition and add words "High level language" It will prevent protocol features inflation by features like "Arm processor register reading" or "Display content of nVidea GPU memory".
Any high level language is abstraction and debugger UI has its own abstraction: it has stack pane, global and local variables pane, breakpoints pane, variable watch pane, hosted editor pane to display and navigate through source code, Server can order source coding modification via passing editor commands.  Command pane and message pane are displayed bellow. Callouts and Popup windows can appear to display requests results. Hoover over source code tokens produces  events which trigger requests to server. Module source opening, code changes, save, etc are reported to the server  as didOpened, didModified, didSaved notifications. Server notifies. UI in the cases when intermediate processing results should be reflected by UI immediately.  
Expected UI behavior should be explained in implementation notes if it is self explainable **like it is done in LSP protocol definition**. These notes are used for future Debugger UI implementors. **Nothing is assumed!**

**Comment by weinand** [comment]
DAP is a high level UI protocol for connecting a debug UI with different debugger backends.
It is not a protocol for debugging "High level languages".

The only reason why it had no support for registers and memory in its initial version is the fact that our first debug adapter was for Node.js (which has no need for this). But it had support for stacks...

Since the arrival of C++ or C# debuggers we see the need to support registers and memory in the protocol so that IDEs that traditionally have strong support for surfacing registers and memory can talk to their debug adapters without having to use private protocols. However, VS Code has "no tradition" in doing this and implementing register or memory view is currently not a priority.
