### ISSUE TITLE
Debugging session state management notifications.

### ISSUE THREAD

**Issue by PavelSosin** [microsoft/debug-adapter-protocol#47]
Debugger client shell be able to manage debugging session state to support remote debugging:
Use case 1: developer **starts** debugging session but wishes to start communication with debugger server only when either main thread is started or 1st break
point is reached.
Use case 2: debugging session has lead to undesired results and developer wishes to **abort** debugging
Use case 3: mutation of application state by developer resulted in undesired results and developer wishes to restore initial application state and **re-start** debugging session without re-opening UI and going through initialization phase - neither server nor client capabilities changed.
Development tools supporting remote debugging like Java and Chrome debuggers support this functionality.

**Comment by weinand** [comment]
Since this project is the Debug Adapter Protocol, it would be great if you could provide more detailed information about the "protocol" you want to propose. E.g. what requests, events, and types are needed to support the feature.

Typically this requires that you have already an implementation where you could explore and prototype the feature.

In addition please see these two VS Code features that might be related to your feature, but their implementation did not require new debug adapter protocol:

- VS Code https://code.visualstudio.com/updates/v1_32#_automatically-open-a-uri-when-debugging-a-server-program
- VS Code started to support Remote Development in the last Insiders (see https://code.visualstudio.com/updates/v1_34#_preview-remote-development). With this it is possible to run every existing debug extension remotely.
