### ISSUE TITLE
Preventing unbounded growth of the variablesReferences mapping

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/debug-adapter-protocol#58]
Resolving `variablesReference`s requires DA implementors to store mapping from variable to underlying implementation in a strong map. That means that all the console evaluations are retained indefinitely and leads to the unbounded memory growth. This is a problem on its own, but it makes things even worse when user wants to analyze memory leaks and explore object graph / retainers.

CDP uses a notion of `objectGroup` to work around it. Console evaluations are done in the `console` group and that group is discarded upon clearing console. DAP already has a `context` field with the `repl` for console. Could we get a signal `contextDiscarded` to clean up our internal maps?

**Comment by int19h** [comment]
I'm not entirely sure about this, but I think that variable references aren't meant to persist beyond a single stop - i.e. `continue`, `stepIn` etc should invalidate them. At least this is what the existing clients assume, so far as I can tell, since they re-eval everything in that case. 

The spec does not say anything about it, though. Perhaps it should?

In fact, it doesn't even say that `variables` request can only be issued while stopped - but how many existing debug adapters will actually handle it properly, unless it is not? (once you start expanding children etc)

In general, some kind of explicit lifetime management for variable references would be nice to have indeed.

**Comment by weinand** [comment]
Please see #60

**Comment by PavelSosin** [comment]
The variable lifetime in any programming language I know is defined by language definition and not by debugger. There is always predefined event which makes variable reference irrelevant. Taking into account the fact that DAP protocol purpose is to connect debugger client UI with debugger server I can't imagine the scenario when the size of variable reference table can impose some risk for client or server. The minimal size of Chrome instance showing purely static content is about 100 Mbyte. The validity of variable reference is a feature of client Client has to observe the same debugger events as effecting variable reference validity: Enter frame, return, running, stopped etc. and all debugger clients always do it. If you are talking about such features as Heap walker, Memory leak detectors, etc. they are normally not a part of debugger but separate applications. For some languages, like Java, they can't be combined with debugger in one server process because they use different port, i.e. require separate network configuration.
Should proper memory handling in the client and server be a part of communication protocol?

**Comment by pavelfeldman** [comment]
@weinand my understanding is that `contextDiscarded` would effectively make the life span of debug console and debug session different. Are we on the same page? Below is a broader context on why it is essential to differentiate the two for web use cases.

In majority of the web use cases, debug session never ends. User launches the web app once and never stops it. Underlying stack will hot-reload modules or user will reload the page manually, but it will all happen within a single debug session. If we don't have a way to clear (discard) the context, all the handles that have been produced by evaluates and outputs become leaky.

Chrome solves this problem by clearing the console upon the target web page reload. Console clears and naturally all the variable handles are released. If that did not happen, logging a single node in your web app would be leaking the entire document along with the global object in the isolate.

**Comment by weinand** [comment]
@pavelfeldman yes, I fully agree with the `contextDiscarded` semantics that allows to decouple console lifetime from debug session lifetime.
I just wanted to mentioned that VS Code currently does not support this decoupling.

**Comment by PavelSosin** [comment]
@isidorn I think that vscode doesn't do it because the problem doesn't really exists. In any Web Scenario Debugger UI session is stateless unless it uses some browser persistency ( very special!) mechanisms. If server is implemented correctly, reports to client debugging session state changes correctly  ( running, stopped, call frame enter and return ) artificial decoupling server and client session lifetime is not necessary.  Since **DAP is built on top of JsonRPC and WebSocket protocols** server is aware about browser page reload. I suppose that correct server implementation has to clear all mapping tables upon client disconnection unless they are persistent and reload them upon the same debugging session identified by session id reconnected. Are the any memory size limit exists? 
Maybe you mean another low level debugging protocol?
Usage of different protocol stacks for DAP and LSP in the same Web IDE is virtually impossible.

**Comment by pavelfeldman** [comment]
@PavelSosin

> The variable lifetime in any programming language I know is defined by language definition and not by debugger

In case of the languages with the garbage collection, debugger retains the objects it gave away handles to. So we don't leak the handles, we leak the actual objects. We can't weak-reference them because we still need to access short-lived objects that were printed in debugger from runtime. JavaScript allows printing objects in debugger console via `console.log` and alike.

V8 allows passing objects across contexts, so we can't associate objects with their contexts and bulk delete handles to them easily. What we can do though is to rely upon the Browser (specific V8 embedder) semantics and wipe out all the handles upon the main page navigation.

That actually sounds like a good idea to me - it takes away the nastiest implications of the long running debugger sessions and makes this request less urgent. It does not solve the memory tools -related concerns though, so `contextDiscarded` still makes sense to me.

**Comment by PavelSosin** [comment]
@pavelfeldman , @weinand 
If the goal of DAP project is unification of communication between debugger client UI and debugger server any feature request implementation should give some benefits for developers and should be feasible and justified for, at least, several debugger implementations. if issue #53 is bug, please clarify what is the real issue which developer experiences or will experience if this issue will not be solved. To estimate the real cost of implementation, please look at official Microsoft marketplace. for VSCode! You will find dozen of debuggers. All of them are potentially effected by protocol changes. 
From my side, I will recall all feature requests related to Kubernetes because they are covered by Squas extension: [Squesh plugin](https://marketplace.visualstudio.com/items?itemName=ilevine.squash)

**Comment by pavelfeldman** [comment]
@wienand: I ended up discarding all the variables upon detecting the navigation & upon explicit clear console event, so this is no longer as urgent as I thought it was. Closing it for now.
