### ISSUE TITLE
clearly spell out the lifetime of IDs used in the protocol

### ISSUE THREAD

**Issue by weinand** [microsoft/debug-adapter-protocol#60]
The general rule for ID lifetime in DAP is:

- IDs of "ephemeral" objects are valid while in the stopped state (or as Gregg said: "until the next 'continue'"). Examples are variable references, goto targets, step-in target, frames.
- IDs of long living objects are valid at least for the lifetime of the debug session (e.g. processes, threads), or even longer (breakpoints, data breakpoints).

This should be more clearly spelled out in the protocol.

**Comment by int19h** [comment]
If we see a sequence of messages from VSCode that does not follow these guidelines - e.g. an attempt to do an "evaluate" immediately after sending "next" (which invalidated all frame IDs, and so the one that comes in "evaluate" is no longer valid), is that a client bug? If so, where should it be filed?

**Comment by weinand** [comment]
yes, I that's a client bug.

@isidorn but it's tricky for the client to figure this out, correct?

**Comment by isidorn** [comment]
Yeah it is a bit tricky, since we do some ui optimisations (e.g we refresh the watch element with a slight timeout and thus it can happend that you get a stale evaluate).
However an issue is welcome, and you can file it here https://github.com/microsoft/vscode and feel free to ping me @isidorn on the issue
