### ISSUE TITLE
Support for some sort of "pending" request in addition to launch and attach

### ISSUE THREAD

**Issue by lanza** [microsoft/debug-adapter-protocol#65]
It would be nice to be able to invert the configuration resolving responsibilities from the editor to the debugger. Currently, you fill out a `launch.json` with a handful of settings and then launch the debugger and the debugger is told what to do.

But for many situations, it's reasonable to just launch the debugger and let the user interact with the debugger itself to start the debug session.

The simplest example of this idea would be CGDB. (`brew install cgdb`, `sudo apt install cgdb`, etc). You start up the process and it immediately drops you into the `gdb` command line interface. Upon launching or attaching the `ncurses` GUI is rendered.

A third sort of request could be used to provide this functionality. `"request": pending` (forgive the horrible name, I can't think of one) which offers no other real configuration and just sends a packet to start the debugger. At this point, you can resolve your target via the debugger's command line interface itself. 

Of course, access to the command line interface would require either backdooring of a proper command line interface or proper support implemented via a "true" debug console -- as spoken about here https://github.com/microsoft/debug-adapter-protocol/issues/45.

**Comment by lanza** [comment]
Here's a quick video demonstrating the ideas from this request and 45. 

https://vimeo.com/347971348

I have a command that just calls `vscode.startDebugging`. This launches my lldb DA implementation with an `attach` request which launches the command line tool `lldb-vscode` in a terminal. At that point `lldb-vscode` brings up it's `CommandInterpreter` in one thread and halts in it's `vscode` communication thread. Upon either launching or attaching to a process `lldb-vscode`'s event watcher thread lets the `VSCode` thread resume and it responds to the `attach` packet.

**Comment by weinand** [comment]
Since you were able to implement this feature without changes of the DAP, I wonder why do you think that a DAP addition is necessary?

**Comment by int19h** [comment]
@lanza
I'm not entirely sure how similar this scenario is, but take a look at the [Python debug adapter](https://github.com/microsoft/ptvsd) - it has a two-part architecture, with one part being the in-proc (relative to the debugged process) debug server that talks DAP over a socket, and the other part being the adapter proper that talks to VSCode over stdio, and tunnels those over the socket to the debug server.

The way that is set up is very similar to what you describe - the user tells what to debug and how by using various command line switches (or, alternatively, a Python API). From the IDE side, however, this is serviced simply as an "attach" request, specifying the host and the port of the debug server to connect to.

It seems to me that your scenario is conceptually similar. From user's perspective, they would still specify either "launch" or "attach" (and you decide which one is semantically closer to its intended purpose), and then other properties in the debug configuration tell your debug adapter that this is an interactive debugger mode.

Thus when user starts debugging e.g. via F5, you'd effectively treat it as "start debugger" - but you can then immediately issue a "stopped" event to indicate that no code is actually running (and fail any incoming "continue", "step" etc requests). When user interacts directly with the debugger to launch the process, you issue a "continued" event to notify the IDE that the state changed. The same technique can be used to implement pausing, stepping etc that is performed via direct interaction. So far as I can tell, the protocol provides all the necessary pieces for this sort of thing already.

**Comment by int19h** [comment]
One thing that is not there, but that would be nice to have for this, is the ability to notify the IDE that "continue", "step" etc are _not supported_ in the current stopped state. For example, the "stopped" event  could have properties such as "canContinue", "canStep", "canEvaluate", "canStackTrace" etc. Or it could be exposed as runtime capabilities - "supportsContinue" etc - that debugger can report changes to via the "capabilities" event that is already there.

Either way, the IDE could then use this information to disable or even hide the corresponding UI elements, such that the user cannot even activate them, and instead gets a visible indication that they're unavailable at the moment.

And this could be potentially useful in other scenarios! For example, there are cases in Python where it's technically impossible to pause fully because the interpreter is running native code. But it's still possible to implement a best-effort pause that would not allow stepping (until native code returns), but which would allow inspecting threads, stacks, and variables, and evaluate code. However, if we do this by failing the step requests, and the debug UI does not reflect the limitations, this might be unnecessarily confusing to the user.

**Comment by lanza** [comment]
> Since you were able to implement this feature without changes of the DAP, I wonder why do you think that a DAP addition is necessary?

Can you please explain your decision making and evaluation criteria? I'm not sure what I'm trying to convince you of. This is clearly a very bad and hacky implementation. It clearly violates the DAP and lies to the client about what is happening. 

This is very clearly a shitty implementation in all capacities. I can't upstream this to llvm. It's code that unambiguously violates the DAP. I can't use this for Facebook official tooling since it provides a janky experience 

@int19h describes in much more detail the problems at hand:

> One thing that is not there, but that would be nice to have for this, is the ability to notify the IDE that "continue", "step" etc are not supported in the current stopped state. For example, the "stopped" event could have properties such as "canContinue", "canStep", "canEvaluate", "canStackTrace" etc. Or it could be exposed as runtime capabilities - "supportsContinue" etc - that debugger can report changes to via the "capabilities" event that is already there.

> Either way, the IDE could then use this information to disable or even hide the corresponding UI elements, such that the user cannot even activate them, and instead gets a visible indication that they're unavailable at the moment.

We are left with a user interface with buttons that don't work and lie about the current situation because the DA is lying to the client and the client doesn't know what else to say.

**Comment by weinand** [comment]
@int19h above you said:
>  Python debug adapter - it has a two-part architecture, with one part being the in-proc (relative to the debugged process) debug server that talks DAP over a socket, and the other part being the adapter proper that talks to VSCode over stdio, and tunnels those over the socket to the debug server.

Why are you using this approach? VS Code can talk directly to the in-proc server. There is no need to have a DA intermediary that connects stdio with the socket.

**Comment by weinand** [comment]
@lanza the decision process is based on tangible protocol proposals and implementations and not on plain feature requests. 

Is suggest that you create a proposal similar to this: #42 and then we can discuss the details.

**Comment by int19h** [comment]
@weinand
Note that "in-proc server" in my comment meant in-proc relative to the debugged process, not in-proc relative to VSCode. Using an in-proc debug _adapter_ would mean that we have two processes rather than three - but we'd still have a socket connection to the debug server that is running inside of the debuggee.

There are two reasons to have the adapter out-of-proc, as well, instead of using VSCode APIs. One is that it allows other editors and IDEs to work with it - e.g. we need it for Python support in Visual Studio proper; and [Vimspector](https://github.com/puremourning/vimspector) is a third-party project that is known to support our adapter. The other reason is that it allows us to implement the adapter itself in Python, rather than TypeScript.

So far as I know - correct me if I'm wrong - the only way to have VSCode connect directly to a socket without _any_ adapter is to use "debugServer", which can only do so for localhost, and is documented for use by extension authors only. If VSCode offers a generic attach-to-DAP-socket facility for the end users, we'd certainly love that! But we'd still need an adapter for launch scenarios, since the adapter is responsible for launching the debuggee in the appropriate way (i.e. such that there is a debug server inside it).

**Comment by int19h** [comment]
@lanza 
I wouldn't describe the current situation as broken, if you implement failing requests with error responses (rather than succeeding and doing nothing). If you respond to a request with a failure, the protocol lets you specify the error message that will be displayed to the end user, and the DAP client has a decently rich API for that - look at `ErrorResponse` and `Message` in the DAP spec. You can even add an URL to a more detailed page where you can provide lengthier explanations, workarounds etc - so the user would know exactly what is going on.

The ability to disable UI elements would _improve_ user experience, in that they wouldn't need to read the error message to understand that this functionality is not available in the current mode. But I think it's more of a convenience thing, and not a show-stopper - especially since the audience for your tool is other developers (and C++ ones at that!).

You'd need to fail unsupported requests anyway, even if VSCode _did_ add a way to disable the corresponding UI elements, since other DAP clients might not support that. And even in VSCode itself, extensions can inject requests into the debug session. Having that implementation would be a good starting point to discuss the UI specifics, since then it's a concrete user experience that can be examined for flaws, and (ideally) end user feedback could be gathered on it.

**Comment by weinand** [comment]
@int19h yes, the link to the VS Code example was misleading because it showed the DA running in-proc the extension host (VS Code).

But what I meant is actually running the DA inside the debuggee but directly talking to it from VS Code. This could easily achieved with this code:

```js
class MockDebugAdapterDescriptorFactory implements DebugAdapterDescriptorFactory {

    createDebugAdapterDescriptor(session: DebugSession): ProviderResult<DebugAdapterDescriptor> {

        // make VS Code connect to DA running inside the debuggee at port 1234
        return new vscode.DebugAdapterServer(1234);
    }
}
```
This is the official way to make VS Code connect to an existing DA running in-proc something else. The Java extension uses exactly this approach.

The port can be a local or remote port. 

But with the new "remote" feature of VS Code, only a local port is sufficient because VS Code connects via the extension host process to that port.

**Comment by int19h** [comment]
@weinand 
We can do the launch via the extension - but again, this is all VSCode-specific. We need to support Visual Studio as well, not just Code. And ideally we want to support anything that can talk DAP and conforms to the specification, such as Vimspector. Having a debug adapter allows us to have a single well-tested implementation for launching on all clients, rather than redoing it for every client.

We also want to minimize the use of TypeScript, because the debug server is by necessity implemented in Python, and it's preferable to have the same language for the adapter, rather than having to use a different one. Better code reuse, more experience with Python on the team etc. 

So the out-of-proc setup that the VSCode architecture allows is a surprisingly good match for our design constraints, and I'm glad that you have accommodated that scenario.

**Comment by gregg-miskelly** [comment]
My two cents worth - As a user, I like it when non-applicable menu items go way because the given command isn't applicable to my environment/language (ex: why are you showing me a memory window, I am java script debugging), but I do NOT like it when a command that normally works suddenly disappears/disables itself because then I need to guess when it is gone/disabled. I would much prefer to see the command, and then I can execute it and it can tell me why it doesn't work. So personally I think the protocol got it right where the initialized event declares capabilities, but we don't have a bunch of 'can' flags on things like stopping events.

**Comment by weinand** [comment]
Thanks Gregg. Your comment reflects our reasoning behind that area of the DAP.

**Comment by int19h** [comment]
On the other hand, VSCode UI already disables (but not hides) those commands outside of a debug session, so they're already modal in that sense. Unlike VS, stepping does not automatically start a new session and "steps into" it - so you need to know that stepping is something that can only be done while debugging (and while this is rather obvious when you know what debugging is, that's not necessarily the case for new devs and non-dev users, as we've found out from our user studies).

With respect to having it in the protocol - the protocol *already* has the ability for the adapter to report dynamically changing capabilities via the "capabilities" event. And that already includes feature flags for e.g. "Step Back", "Restart Frame", "Go To" (Set Next Statement) etc. So some precedent for this kind of thing is already there; I'm not sure how the UI reflects such changes today, if it does. 

But yes, I agree, this kind of approach would need some way to explain what's going on. If the command is hidden entirely, that's unnecessarily confusing. But if it's disabled, its tooltip could explain why it's not applicable in the current context.
