### ISSUE TITLE
Semantics of "restart" are unclear

### ISSUE THREAD

**Issue by int19h** [microsoft/debug-adapter-protocol#73]
The specification for the "restart" request says:

> Restarts a debug session. If the capability ‘supportsRestartRequest’ is missing or has the value false, the client will implement ‘restart’ by terminating the debug adapter first and then launching it anew. A debug adapter can override this default behaviour by implementing a restart request and setting the capability ‘supportsRestartRequest’ to true.

This does not explain what exactly "restart a debug session" means - i.e. what is the expected behavior of the adapter when it decides to implement this request by itself. In particular, the description of what the client does if the request is not supported says that the _adapter_ is terminated and re-launched, but it says nothing at all about the debuggee.

This could be inferred from the exact manner in which the adapter is terminated; but this isn't mentioned - is it just closing the connection? Sending "terminate"? Sending "disconnect" (and if so, what is the value of "terminateDebuggee")?

**Comment by weinand** [comment]
The semantics of "Restart" is exactly what the user would expect when he presses the red "Stop" button and then the green "Start Debugging" button.

**Comment by int19h** [comment]
So, to clarify - in the case of "attach", that would be disconnecting and then immediately re-attaching to the same target?

**Comment by weinand** [comment]
yes.

**Comment by haneefdm** [comment]
I am having the same problem understanding. For an 'attach' session, if a restart simply does a 'detach' (or disconnect) and immediately do an 'attach' isn't that basically a 'null' operation? I am sure I am missing something.

Can an implementation simply ignore the request and pretend that it has 'restart'ed? If the target was running when restart is called, I can simply pause the target while pretending.

**Comment by weinand** [comment]
@haneefdm 
"restart sequence" means:
**_terminate current debug session via the disconnect request and immediately start a new session via the launch or attach request_**

For the "launch" case "restart" can be used to pickup source changes that are not automatically picked up while the program is running.

For the "attach" case "restart" has no direct effect on the debug target because the debug target continues running. But it still might have an effect on debugging because the debug adapter is restarted and this could pick up changes to files that the debug adapter uses, e.g. source maps.

**Comment by haneefdm** [comment]
Thanks. The 'launch' case was very clear. I see what you mean about 'attach'

**Comment by int19h** [comment]
Thanks, @weinand! It looks like all the ambiguities have been resolved, so I'll close the issue.
